apiVersion: v1
kind: ConfigMap
metadata:
  name: opsmx-provider-config
data:
  providerConfig: |
    application: sreejihttestapp
    user: admin
    gateUrl: 'https://isd-argocd.isd-dev.opsmx.net/'
    lifetimeMinutes: 3
    intervalTime: 3
    lookBackType: sliding
    gitops: true
    passScore: 90
    serviceList:
    - metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
      baselineMetricScope: "isd-argofull,{{env.STABLE_POD_HASH}},junaid-on-job"
      canaryMetricScope: "isd-argofull,{{env.LATEST_POD_HASH}},junaid-on-job"
      metricTemplateName: "opsmx-metric-template"
