---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-acc 
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-acc
rules:
  - apiGroups:
      - "batch"
    resources:
      - jobs/status
    verbs:
      - get
      - list
      - patch
  - apiGroups:	
      - ""	
    resources:	
      - pods	
    verbs:	
      - get	
      - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-acc
  namespace: argocd 
subjects:
  - kind: ServiceAccount
    name: job-acc
    namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-acc
