apiVersion: batch/v1
kind: Job
metadata:
  generateName: check-rule-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    spec:
      containers:
          image: debian
          command: ["printenv"]
          name: gitcheck
      restartPolicy: Never
  backoffLimit: 4
