apiVersion: batch/v1
kind: Job
metadata:
  generateName: check-rule-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
        - command: ["printenv"]
          image: debian
          name: command-demo-container
      restartPolicy: Never
