apiVersion: batch/v1
kind: Job
metadata:
  generateName: check-rule-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  template:
    containers:
    - name: command-demo-container
      image: debian
      command: ["printenv"]
    restartPolicy: Never
  backoffLimit: 2
