apiVersion: v1
kind: Pod
metadata:
  generateName: check-rule-
  annotations:
    argocd.argoproj.io/hook: PreSync
spec:
  containers:
  - name: command-demo-container
    image: debian
    command: ["printenv"]
  restartPolicy: Never
